name: Build and Publish Docker image
concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.ref }}
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    schedule:
        - cron: '0 4 * * *'
jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: ${{ runner.temp }}/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Login to GitHub Container Registry
              uses: docker/login-action@3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: |
                      ghcr.io/munezaclovis/frankenphp:latest
                      ghcr.io/munezaclovis/frankenphp:${{ github.sha }}
                  platforms: linux/amd64,linux/arm64
                  cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
                  cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

            - name: Move cache
              run: |
                  rm -rf ${{ runner.temp }}/.buildx-cache
                  mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
